# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMinimumSize(QtCore.QSize(960, 600))
        self.centralwidget.setMaximumSize(QtCore.QSize(960, 600))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.drop_shadow_layout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.drop_shadow_layout.setContentsMargins(11, 11, 11, 11)
        self.drop_shadow_layout.setSpacing(7)
        self.drop_shadow_layout.setObjectName("drop_shadow_layout")
        self.drop_shadow_frame = QtWidgets.QFrame(self.centralwidget)
        self.drop_shadow_frame.setStyleSheet("QFrame{\n"
"border-radius：10px;\n"
"}\n"
"QFrame#drop_shadow_frame{\n"
"border-radius：10px;\n"
"border-image: url(\"./img/bg.png\");\n"
"}")
        self.drop_shadow_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.drop_shadow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.drop_shadow_frame.setObjectName("drop_shadow_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.drop_shadow_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.title_bar.setStyleSheet("background-color:none")
        self.title_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_title = QtWidgets.QFrame(self.title_bar)
        self.frame_title.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_title.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("OPPOSans")
        font.setPointSize(14)
        self.frame_title.setFont(font)
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_title)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_title.setFont(font)
        self.label_title.setCursor(QtGui.QCursor(QtCore.Qt.SizeAllCursor))
        self.label_title.setStyleSheet("QLabel#label_title{\n"
"color: rgb(57, 57, 57);\n"
"padding-left:15px;}")
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_7.addWidget(self.label_title)
        self.horizontalLayout.addWidget(self.frame_title)
        self.frame_btns = QtWidgets.QFrame(self.title_bar)
        self.frame_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_btns)
        self.horizontalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_theme = QtWidgets.QCheckBox(self.frame_btns)
        self.checkBox_theme.setMinimumSize(QtCore.QSize(0, 0))
        self.checkBox_theme.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.checkBox_theme.setStyleSheet("QCheckBox {\n"
"    spacing: 5px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 32px;\n"
"    height: 32px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    image: url(./img/slider.png);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    image: url(./img/slider_check.png);\n"
"}\n"
"\n"
"")
        self.checkBox_theme.setText("")
        self.checkBox_theme.setObjectName("checkBox_theme")
        self.horizontalLayout_3.addWidget(self.checkBox_theme)
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_minimize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_minimize.setMaximumSize(QtCore.QSize(16, 16))
        self.btn_minimize.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:4px;\n"
"    background-color:rgb(85, 255, 127,255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(85, 255, 127, 150);\n"
"}")
        self.btn_minimize.setText("")
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_3.addWidget(self.btn_minimize)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns)
        self.btn_close.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_close.setMaximumSize(QtCore.QSize(16, 16))
        self.btn_close.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:4px;\n"
"    background-color:rgb(255, 0, 0,255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255, 0, 0, 150);\n"
"}")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_3.addWidget(self.btn_close)
        self.horizontalLayout.addWidget(self.frame_btns)
        self.verticalLayout.addWidget(self.title_bar)
        self.content_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.content_bar.setAutoFillBackground(False)
        self.content_bar.setStyleSheet("background-color:none;\n"
"border:none;\n"
"border-radius:5px;\n"
"\n"
"\n"
"\n"
"")
        self.content_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_bar.setObjectName("content_bar")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.content_bar)
        self.verticalLayout_4.setContentsMargins(0, 0, 15, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.content_bar)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_home)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_content_home = QtWidgets.QFrame(self.page_home)
        self.frame_content_home.setStyleSheet("")
        self.frame_content_home.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content_home.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content_home.setObjectName("frame_content_home")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_content_home)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_launch_top = QtWidgets.QFrame(self.frame_content_home)
        self.frame_launch_top.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_launch_top.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_launch_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_launch_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_launch_top.setObjectName("frame_launch_top")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_launch_top)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_2 = QtWidgets.QFrame(self.frame_launch_top)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6.addWidget(self.frame_2)
        self.frame_preference = QtWidgets.QFrame(self.frame_launch_top)
        self.frame_preference.setMaximumSize(QtCore.QSize(50, 50))
        self.frame_preference.setStyleSheet("padding:5px;")
        self.frame_preference.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_preference.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_preference.setObjectName("frame_preference")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_preference)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn_preference = QtWidgets.QPushButton(self.frame_preference)
        self.btn_preference.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_preference.setStyleSheet("QPushButton{\n"
"    border:2px solid orange;\n"
"    border-radius:15px;\n"
"    background-color:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:orange;\n"
"}")
        self.btn_preference.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("."), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_preference.setIcon(icon)
        self.btn_preference.setCheckable(False)
        self.btn_preference.setObjectName("btn_preference")
        self.horizontalLayout_8.addWidget(self.btn_preference)
        self.horizontalLayout_6.addWidget(self.frame_preference)
        self.verticalLayout_6.addWidget(self.frame_launch_top)
        self.frame_launch_middle = QtWidgets.QFrame(self.frame_content_home)
        self.frame_launch_middle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_launch_middle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_launch_middle.setObjectName("frame_launch_middle")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_launch_middle)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_bg_image = QtWidgets.QFrame(self.frame_launch_middle)
        self.frame_bg_image.setStyleSheet("")
        self.frame_bg_image.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bg_image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bg_image.setObjectName("frame_bg_image")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_bg_image)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_web_links = QtWidgets.QFrame(self.frame_bg_image)
        self.frame_web_links.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_web_links.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_web_links.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_web_links.setObjectName("frame_web_links")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_web_links)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.btn_web1 = QtWidgets.QPushButton(self.frame_web_links)
        self.btn_web1.setText("")
        self.btn_web1.setObjectName("btn_web1")
        self.verticalLayout_12.addWidget(self.btn_web1)
        self.btn_web2 = QtWidgets.QPushButton(self.frame_web_links)
        self.btn_web2.setText("")
        self.btn_web2.setObjectName("btn_web2")
        self.verticalLayout_12.addWidget(self.btn_web2)
        self.btn_web3 = QtWidgets.QPushButton(self.frame_web_links)
        self.btn_web3.setText("")
        self.btn_web3.setObjectName("btn_web3")
        self.verticalLayout_12.addWidget(self.btn_web3)
        self.btn_web4 = QtWidgets.QPushButton(self.frame_web_links)
        self.btn_web4.setText("")
        self.btn_web4.setObjectName("btn_web4")
        self.verticalLayout_12.addWidget(self.btn_web4)
        self.horizontalLayout_14.addWidget(self.frame_web_links)
        self.frame_5 = QtWidgets.QFrame(self.frame_bg_image)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_14.addWidget(self.frame_5)
        self.horizontalLayout_11.addWidget(self.frame_bg_image)
        self.verticalLayout_6.addWidget(self.frame_launch_middle)
        self.frame_launch_button = QtWidgets.QFrame(self.frame_content_home)
        self.frame_launch_button.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_launch_button.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_launch_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_launch_button.setObjectName("frame_launch_button")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_launch_button)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_launch_button_space = QtWidgets.QFrame(self.frame_launch_button)
        self.frame_launch_button_space.setMinimumSize(QtCore.QSize(500, 100))
        self.frame_launch_button_space.setMaximumSize(QtCore.QSize(700, 100))
        self.frame_launch_button_space.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_launch_button_space.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_launch_button_space.setObjectName("frame_launch_button_space")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_launch_button_space)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.blender_info = QtWidgets.QLabel(self.frame_launch_button_space)
        self.blender_info.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(9)
        self.blender_info.setFont(font)
        self.blender_info.setStyleSheet("padding:20px")
        self.blender_info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.blender_info.setObjectName("blender_info")
        self.verticalLayout_7.addWidget(self.blender_info)
        self.horizontalLayout_4.addWidget(self.frame_launch_button_space)
        self.frame_launch_button_2 = QtWidgets.QFrame(self.frame_launch_button)
        self.frame_launch_button_2.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_launch_button_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_launch_button_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_launch_button_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_launch_button_2.setObjectName("frame_launch_button_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_launch_button_2)
        self.verticalLayout_9.setContentsMargins(0, 0, 4, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.comboBox_bl_version = QtWidgets.QComboBox(self.frame_launch_button_2)
        self.comboBox_bl_version.setMinimumSize(QtCore.QSize(0, 100))
        self.comboBox_bl_version.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBox_bl_version.setFont(font)
        self.comboBox_bl_version.setMouseTracking(False)
        self.comboBox_bl_version.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_bl_version.setStyleSheet("QComboBox{\n"
"    background-color:rgb(255, 170, 0);\n"
"    color:white;\n"
"    padding:20px;\n"
"\n"
"    border-top-left-radius:15px;\n"
"    border-bottom-left-radius:15px;\n"
"    border-top-right-radius:0px;\n"
"    border-bottom-right-radius:0px;\n"
"}\n"
"QComboBox:hover{\n"
"    background-color:rgb(255, 220, 0);\n"
"    color:white;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
" \n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}    \n"
"\n"
"QComboBox::down-arrow {\n"
"    border-image: url(./img/arrow_down.png);\n"
"}")
        self.comboBox_bl_version.setEditable(False)
        self.comboBox_bl_version.setCurrentText("")
        self.comboBox_bl_version.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox_bl_version.setMinimumContentsLength(0)
        self.comboBox_bl_version.setIconSize(QtCore.QSize(20, 20))
        self.comboBox_bl_version.setFrame(True)
        self.comboBox_bl_version.setObjectName("comboBox_bl_version")
        self.verticalLayout_9.addWidget(self.comboBox_bl_version)
        self.horizontalLayout_4.addWidget(self.frame_launch_button_2)
        self.frame_launc_button_combobox = QtWidgets.QFrame(self.frame_launch_button)
        self.frame_launc_button_combobox.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_launc_button_combobox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_launc_button_combobox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_launc_button_combobox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_launc_button_combobox.setObjectName("frame_launc_button_combobox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_launc_button_combobox)
        self.verticalLayout_8.setContentsMargins(0, 0, 5, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.launch_button = QtWidgets.QPushButton(self.frame_launc_button_combobox)
        self.launch_button.setMinimumSize(QtCore.QSize(0, 100))
        self.launch_button.setMaximumSize(QtCore.QSize(120, 100))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.launch_button.setFont(font)
        self.launch_button.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    background-color:rgb(255, 170, 0);\n"
"    border:none;\n"
"    border-top-left-radius:0px;\n"
"    border-bottom-left-radius:0px;\n"
"    border-top-right-radius:15px;\n"
"    border-bottom-right-radius:15px;\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    color:white;\n"
"    background-color:rgb(255, 220, 0);\n"
"}")
        self.launch_button.setObjectName("launch_button")
        self.verticalLayout_8.addWidget(self.launch_button)
        self.horizontalLayout_4.addWidget(self.frame_launc_button_combobox)
        self.verticalLayout_6.addWidget(self.frame_launch_button)
        self.verticalLayout_5.addWidget(self.frame_content_home)
        self.stackedWidget.addWidget(self.page_home)
        self.page_pref = QtWidgets.QWidget()
        self.page_pref.setObjectName("page_pref")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page_pref)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_pref = QtWidgets.QFrame(self.page_pref)
        self.frame_pref.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pref.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pref.setObjectName("frame_pref")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_pref)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_pref_top = QtWidgets.QFrame(self.frame_pref)
        self.frame_pref_top.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_pref_top.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_pref_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pref_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pref_top.setObjectName("frame_pref_top")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_pref_top)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_3 = QtWidgets.QFrame(self.frame_pref_top)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_12.addWidget(self.frame_3)
        self.frame_preference_2 = QtWidgets.QFrame(self.frame_pref_top)
        self.frame_preference_2.setMaximumSize(QtCore.QSize(50, 50))
        self.frame_preference_2.setStyleSheet("padding:5px;")
        self.frame_preference_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_preference_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_preference_2.setObjectName("frame_preference_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_preference_2)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.btn_home = QtWidgets.QPushButton(self.frame_preference_2)
        self.btn_home.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_home.setStyleSheet("QPushButton{\n"
"    border:2px solid orange;\n"
"    border-radius:15px;\n"
"    background-color:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:orange;\n"
"}")
        self.btn_home.setText("")
        icon = QtGui.QIcon.fromTheme("./img/arrow_down.png")
        self.btn_home.setIcon(icon)
        self.btn_home.setObjectName("btn_home")
        self.horizontalLayout_13.addWidget(self.btn_home)
        self.horizontalLayout_12.addWidget(self.frame_preference_2)
        self.verticalLayout_2.addWidget(self.frame_pref_top)
        self.frame_pref_content = QtWidgets.QFrame(self.frame_pref)
        self.frame_pref_content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_pref_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pref_content.setObjectName("frame_pref_content")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_pref_content)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame = QtWidgets.QFrame(self.frame_pref_content)
        self.frame.setMinimumSize(QtCore.QSize(700, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_10.setContentsMargins(40, 0, 0, 30)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.blender_folder_list = DropBlenderFolders(self.frame)
        self.blender_folder_list.setMinimumSize(QtCore.QSize(800, 400))
        self.blender_folder_list.setMaximumSize(QtCore.QSize(800, 400))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.blender_folder_list.setFont(font)
        self.blender_folder_list.setAcceptDrops(True)
        self.blender_folder_list.setStyleSheet("QListView{\n"
"border:2 solid orange;\n"
"border-radius:5px;\n"
"alternate-background-color:orange;\n"
"}\n"
"/* 行与行之间交替颜色不同 */\n"
"/* setAlternatingRowColors(true); */\n"
"QListView::item:alternate {\n"
"    background:#D9FAFF;\n"
"}\n"
"QListView::item:selected {\n"
"    color:white;\n"
"    background-color:orange;\n"
"}\n"
"/* 鼠标县浮在条目上 */\n"
"QListView::item::hover {\n"
"    background:rgb(0, 170, 255);\n"
"    padding:10px;\n"
"}\n"
"\n"
"QScrollBar{\n"
"background:blue;\n"
"}\n"
"\n"
"QScrollBar::handle\n"
"{\n"
"    width:10px;\n"
"    background:orange;\n"
"    border-radius:10px;   \n"
"    min-height:20;\n"
"}\n"
"")
        self.blender_folder_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.blender_folder_list.setObjectName("blender_folder_list")
        self.horizontalLayout_10.addWidget(self.blender_folder_list)
        self.horizontalLayout_9.addWidget(self.frame)
        self.frame_pref_side = QtWidgets.QFrame(self.frame_pref_content)
        self.frame_pref_side.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_pref_side.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_pref_side.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_pref_side.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pref_side.setObjectName("frame_pref_side")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_pref_side)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_add_btn = QtWidgets.QFrame(self.frame_pref_side)
        self.frame_add_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.frame_add_btn.setMaximumSize(QtCore.QSize(50, 120))
        self.frame_add_btn.setStyleSheet("")
        self.frame_add_btn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_add_btn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_add_btn.setObjectName("frame_add_btn")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_add_btn)
        self.verticalLayout_10.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.btn_list_remove = RemoveButton(self.frame_add_btn)
        self.btn_list_remove.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_list_remove.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_list_remove.setAcceptDrops(False)
        self.btn_list_remove.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_list_remove.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background-color:orange;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(255, 220, 0);\n"
"}")
        self.btn_list_remove.setText("")
        self.btn_list_remove.setIconSize(QtCore.QSize(20, 20))
        self.btn_list_remove.setObjectName("btn_list_remove")
        self.verticalLayout_10.addWidget(self.btn_list_remove)
        self.btn_list_refresh = QtWidgets.QPushButton(self.frame_add_btn)
        self.btn_list_refresh.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_list_refresh.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_list_refresh.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_list_refresh.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background-color:orange;\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(255, 220, 0);\n"
"}")
        self.btn_list_refresh.setText("")
        self.btn_list_refresh.setIconSize(QtCore.QSize(20, 20))
        self.btn_list_refresh.setObjectName("btn_list_refresh")
        self.verticalLayout_10.addWidget(self.btn_list_refresh)
        self.verticalLayout_11.addWidget(self.frame_add_btn)
        self.frame_add_fill = QtWidgets.QFrame(self.frame_pref_side)
        self.frame_add_fill.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_add_fill.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_add_fill.setObjectName("frame_add_fill")
        self.verticalLayout_11.addWidget(self.frame_add_fill)
        self.horizontalLayout_9.addWidget(self.frame_pref_side)
        self.verticalLayout_2.addWidget(self.frame_pref_content)
        self.horizontalLayout_5.addWidget(self.frame_pref)
        self.stackedWidget.addWidget(self.page_pref)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.content_bar)
        self.credits_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.credits_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.credits_bar.setStyleSheet("background-color:none")
        self.credits_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.credits_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.credits_bar.setObjectName("credits_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.credits_bar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_label_credits = QtWidgets.QFrame(self.credits_bar)
        self.frame_label_credits.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_label_credits.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_label_credits.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_credits.setObjectName("frame_label_credits")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_label_credits)
        self.verticalLayout_3.setContentsMargins(10, 0, 0, 5)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_credits = QtWidgets.QLabel(self.frame_label_credits)
        font = QtGui.QFont()
        font.setFamily("OPPOSans")
        font.setPointSize(6)
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("QLabel#label_credits{color:rgb(170, 170, 170);}")
        self.label_credits.setObjectName("label_credits")
        self.verticalLayout_3.addWidget(self.label_credits)
        self.horizontalLayout_2.addWidget(self.frame_label_credits)
        self.verticalLayout.addWidget(self.credits_bar)
        self.drop_shadow_layout.addWidget(self.drop_shadow_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Blender Launcher"))
        self.label_title.setText(_translate("MainWindow", "Blender Launcher"))
        self.blender_info.setText(_translate("MainWindow", "Set Your Blender Folder First!"))
        self.launch_button.setText(_translate("MainWindow", "Launch!"))
        self.label_credits.setText(_translate("MainWindow", "By Atticus_Id"))
from ui_functions import DropBlenderFolders, RemoveButton
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
